import { UnblurryMark } from '../components/UnblurryLogo';

const LAST_UPDATED = 'February 26, 2026';

export default function TermsOfUse() {
  return (
    <div className="min-h-screen bg-bg-primary">
      {/* Nav */}
      <nav className="border-b border-border py-4">
        <div className="mx-auto flex items-center justify-between px-6" style={{ maxWidth: 720 }}>
          <a href="./landing.html" className="inline-flex items-center gap-[6px]">
            <UnblurryMark size={20} className="text-primary-500" />
            <span className="font-heading text-[16px] font-bold text-text-primary">Unblurry</span>
          </a>
          <a href="./privacy.html" className="text-[13px] font-medium text-text-secondary hover:text-text-primary">
            Privacy Policy
          </a>
        </div>
      </nav>

      {/* Content */}
      <main className="mx-auto px-6 py-12 md:py-16" style={{ maxWidth: 720 }}>
        <h1 className="font-heading text-[32px] font-bold text-text-primary">Terms of Use</h1>
        <p className="mt-2 text-[14px] text-text-tertiary">Last updated: {LAST_UPDATED}</p>

        <div className="mt-10 flex flex-col gap-8 text-[15px] leading-relaxed text-text-secondary">
          <section>
            <h2 className="font-heading text-[20px] font-bold text-text-primary">Acceptance of terms</h2>
            <p className="mt-3">
              By downloading, installing, or using Unblurry, you agree to these terms. If you do not agree,
              do not use the app.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-[20px] font-bold text-text-primary">What Unblurry is</h2>
            <p className="mt-3">
              Unblurry is a free desktop application for macOS that helps you reflect on your work sessions.
              It captures window titles, accepts voluntary feeling logs, and uses AI to generate behavioral
              analysis reports. All data is stored locally on your device.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-[20px] font-bold text-text-primary">Your API key</h2>
            <p className="mt-3">
              Unblurry uses a Bring Your Own Key (BYOK) model. You provide your own Google Gemini API key
              to generate reports. You are responsible for:
            </p>
            <ul className="mt-3 list-disc pl-6 flex flex-col gap-2">
              <li>Any costs incurred from your Gemini API usage.</li>
              <li>Keeping your API key secure.</li>
              <li>Complying with Google's API terms of service.</li>
            </ul>
            <p className="mt-3">
              We do not store, transmit, or have access to your API key on any server.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-[20px] font-bold text-text-primary">AI-generated content</h2>
            <p className="mt-3">
              The behavioral analysis reports generated by Unblurry are produced by AI and are for
              <strong> informational purposes only</strong>. They are not professional, medical, or
              psychological advice. The AI may produce inaccurate, incomplete, or misleading analysis.
              Do not rely on these reports as a substitute for professional guidance.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-[20px] font-bold text-text-primary">No guarantees</h2>
            <p className="mt-3">
              We do our best to make Unblurry reliable, but we cannot guarantee that the app will always
              work perfectly, be free of bugs, or never crash. Use it at your own discretion.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-[20px] font-bold text-text-primary">Responsibility</h2>
            <p className="mt-3">
              We are not responsible for any damages that may result from using Unblurry, including but
              not limited to data loss, lost work, or interruptions. Since all data is stored locally on
              your device, we recommend keeping your own backups of anything important.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-[20px] font-bold text-text-primary">Your data</h2>
            <p className="mt-3">
              You own all data generated by your use of Unblurry. Since all data is stored locally on your
              device, you are solely responsible for backing up and protecting your data. We cannot recover
              lost data because we never have access to it.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-[20px] font-bold text-text-primary">Intellectual property</h2>
            <p className="mt-3">
              Unblurry, including its name, logo, design, and code, is the intellectual property of Imane
              Idrissi (<a href="https://github.com/Imane-Idrissi" target="_blank" rel="noopener noreferrer" className="text-primary-500 underline">@Imane-Idrissi</a> on GitHub). You may not copy, modify, distribute, or create derivative works of the app without
              prior written permission.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-[20px] font-bold text-text-primary">Changes to these terms</h2>
            <p className="mt-3">
              We may update these terms at any time. The revised version will be posted on this page with an
              updated date. Continued use of the app after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-[20px] font-bold text-text-primary">Contact</h2>
            <p className="mt-3">
              If you have questions about these terms, you can{' '}
              <a
                href="https://github.com/Imane-Idrissi/self-reflection-app/issues"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary-500 underline"
              >
                open an issue on GitHub
              </a>
              .
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border py-6">
        <div className="mx-auto flex items-center justify-between px-6" style={{ maxWidth: 720 }}>
          <span className="inline-flex items-center gap-[6px] text-[13px] text-text-tertiary">
            <UnblurryMark size={14} className="text-text-tertiary" />
            Unblurry
          </span>
          <span className="text-[13px] text-text-tertiary">&copy; {new Date().getFullYear()} Imane Idrissi. All rights reserved.</span>
        </div>
      </footer>
    </div>
  );
}
